#!/usr/bin/env node
const path = require('path');
const fs = require('fs');

const rbql_home_dir = __dirname;


function replace_all(src, search, replacement) {
    return src.split(search).join(replacement);
}


function escape_string_literal_backtick(src) {
    src = replace_all(src, '\\', '\\\\');
    src = replace_all(src, "`", "\\`");
    src = replace_all(src, "${", "\\${");
    src = "`" + src + "`";
    return src;
}


function read_engine_text() {
    try {
        return fs.readFileSync(path.join(rbql_home_dir, 'rbql.js'), 'utf-8');
    } catch (e) {
        return '';
    }
}


function build_engine_text() {
    let proto_engine_dir = path.join(rbql_home_dir, 'proto_engine');
    let builder_text = fs.readFileSync(path.join(proto_engine_dir, 'builder.js'), 'utf-8');
    let template_text = fs.readFileSync(path.join(proto_engine_dir, 'template.js'), 'utf-8');
    let marker = 'codegeneration_pseudo_function_include_combine("template.js")';
    let do_not_edit_warning = '// Do not edit!\n// This file was autogenerated from builder.js and template.js\n';
    let engine_text = do_not_edit_warning + builder_text.replace(marker, escape_string_literal_backtick(template_text)) + do_not_edit_warning;
    return engine_text;
}


function build_engine() {
    let engine_text = build_engine_text();
    fs.writeFileSync(path.join(rbql_home_dir, 'rbql.js'), engine_text, 'utf-8');
}


module.exports.build_engine = build_engine;
module.exports.read_engine_text = read_engine_text;
module.exports.build_engine_text = build_engine_text;

if (require.main === module) {
    build_engine();
}


